# Made using ReTask by JustSoftware & cresqnt

CPU_INTENSIVE_HIGH_ACCURACY_SLEEP = True
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController
from mousekey import MouseKey
from time import sleep, perf_counter
from fractions import Fraction

NONVIP = False
SCALE = float(Fraction(342, 277))

kc = KeyboardController()
mc = MouseController()
mkey = MouseKey()

pynput_special_keys = {
    "Key.alt": Key.alt,
    "Key.alt_l": Key.alt_l,
    "Key.alt_r": Key.alt_r,
    "Key.backspace": Key.backspace,
    "Key.caps_lock": Key.caps_lock,
    "Key.cmd": Key.cmd,
    "Key.cmd_l": Key.cmd_l,
    "Key.cmd_r": Key.cmd_r,
    "Key.ctrl": Key.ctrl,
    "Key.ctrl_l": Key.ctrl_l,
    "Key.ctrl_r": Key.ctrl_r,
    "Key.delete": Key.delete,
    "Key.down": Key.down,
    "Key.end": Key.end,
    "Key.enter": Key.enter,
    "Key.esc": Key.esc,
    "Key.f1": Key.f1,
    "Key.f2": Key.f2,
    "Key.f3": Key.f3,
    "Key.f4": Key.f4,
    "Key.f5": Key.f5,
    "Key.f6": Key.f6,
    "Key.f7": Key.f7,
    "Key.f8": Key.f8,
    "Key.f9": Key.f9,
    "Key.f10": Key.f10,
    "Key.f11": Key.f11,
    "Key.f12": Key.f12,
    "Key.home": Key.home,
    "Key.insert": Key.insert,
    "Key.left": Key.left,
    "Key.menu": Key.menu,
    "Key.num_lock": Key.num_lock,
    "Key.page_down": Key.page_down,
    "Key.page_up": Key.page_up,
    "Key.pause": Key.pause,
    "Key.print_screen": Key.print_screen,
    "Key.right": Key.right,
    "Key.scroll_lock": Key.scroll_lock,
    "Key.shift": Key.shift,
    "Key.shift_l": Key.shift_l,
    "Key.shift_r": Key.shift_r,
    "Key.space": Key.space,
    "Key.tab": Key.tab,
    "Key.up": Key.up
}

pynput_special_buttons = {
    "Button.left": Button.left,
    "Button.right": Button.right,
    "Button.middle": Button.middle
}

def run_macro(macro, delay=2):
    sleep(delay)

    for action in macro:
        match action["type"]:
            case "wait":
                if NONVIP:
                    sleep((action["duration"] * SCALE) / 1000.0)
                else:
                    sleep(action["duration"] / 1000.0)
            case "key_press":
                key = action["key"]
                kc.press(pynput_special_keys.get(key, key))
            case "key_release":
                key = action["key"]
                kc.release(pynput_special_keys.get(key, key))
            case "mouse_movement":
                mkey.move_to(int(action["x"]), int(action["y"]))
            case "mouse_press":
                mc.press(pynput_special_buttons[action["button"]])
            case "mouse_release":
                mc.release(pynput_special_buttons[action["button"]])
            case "mouse_scroll":
                if "x" in action:
                    mkey.move_to(int(action["x"]), int(action["y"]))
                mc.scroll(action["dx"], action["dy"])


macro_actions = [{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 53},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 1032},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 101},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 719},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 128},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 445},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 126},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 1022},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 9},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 312},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 18},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 550},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 223},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 945},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 150},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1391},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 166},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1038},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 149},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 436},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 955},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 291},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 533},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 170},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 226},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 331},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 96},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 88},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 131},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 435},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 76},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 104},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 197},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 339},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 67},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 166},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 73},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 435},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 94},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 88},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 118},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 452},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 99},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 111},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 223},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 259},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 105},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 116},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 84},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 403},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 78},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 102},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 85},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 427},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 77},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 104},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 159},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 396},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 8},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 228},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 33},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 420},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 21},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 222},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 2},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 477},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 6},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 187},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 3031},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 278},
{'type': 'key_press', 'key': 'e'},
{'type': 'wait', 'duration': 123},
{'type': 'key_release', 'key': 'e'},
{'type': 'wait', 'duration': 87},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 206},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 187},
{'type': 'key_press', 'key': 'e'},
{'type': 'wait', 'duration': 192},
{'type': 'key_release', 'key': 'e'},
{'type': 'wait', 'duration': 134},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 188},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 101},
{'type': 'key_press', 'key': 'e'},
{'type': 'wait', 'duration': 228},
{'type': 'key_release', 'key': 'e'}]

if __name__ == "__main__":
    run_macro([{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 53},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 1032},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 101},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 719},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 128},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 445},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 126},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 1022},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 9},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 312},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 18},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 550},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 223},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 945},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 150},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1391},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 166},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1038},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 149},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 436},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 955},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 291},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 533},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 170},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 226},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 331},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 96},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 88},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 131},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 435},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 76},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 104},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 197},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 339},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 67},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 166},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 73},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 435},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 94},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 88},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 118},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 452},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 99},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 111},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 223},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 259},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 105},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 116},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 84},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 403},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 78},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 102},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 85},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 427},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 77},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 104},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 159},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 396},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 8},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 228},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 33},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 420},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 21},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 222},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 2},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 477},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 6},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 187},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 3031},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 278},
{'type': 'key_press', 'key': 'e'},
{'type': 'wait', 'duration': 123},
{'type': 'key_release', 'key': 'e'},
{'type': 'wait', 'duration': 87},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 206},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 187},
{'type': 'key_press', 'key': 'e'},
{'type': 'wait', 'duration': 192},
{'type': 'key_release', 'key': 'e'},
{'type': 'wait', 'duration': 134},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 188},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 101},
{'type': 'key_press', 'key': 'e'},
{'type': 'wait', 'duration': 228},
{'type': 'key_release', 'key': 'e'}])