# Made using ReTask by JustSoftware & cresqnt

CPU_INTENSIVE_HIGH_ACCURACY_SLEEP = True
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController
from mousekey import MouseKey
from time import sleep, perf_counter

kc = KeyboardController()
mc = MouseController()
mkey = MouseKey()

pynput_special_keys = {
    "Key.alt": Key.alt,
    "Key.alt_l": Key.alt_l,
    "Key.alt_r": Key.alt_r,
    "Key.backspace": Key.backspace,
    "Key.caps_lock": Key.caps_lock,
    "Key.cmd": Key.cmd,
    "Key.cmd_l": Key.cmd_l,
    "Key.cmd_r": Key.cmd_r,
    "Key.ctrl": Key.ctrl,
    "Key.ctrl_l": Key.ctrl_l,
    "Key.ctrl_r": Key.ctrl_r,
    "Key.delete": Key.delete,
    "Key.down": Key.down,
    "Key.end": Key.end,
    "Key.enter": Key.enter,
    "Key.esc": Key.esc,
    "Key.f1": Key.f1,
    "Key.f2": Key.f2,
    "Key.f3": Key.f3,
    "Key.f4": Key.f4,
    "Key.f5": Key.f5,
    "Key.f6": Key.f6,
    "Key.f7": Key.f7,
    "Key.f8": Key.f8,
    "Key.f9": Key.f9,
    "Key.f10": Key.f10,
    "Key.f11": Key.f11,
    "Key.f12": Key.f12,
    "Key.home": Key.home,
    "Key.insert": Key.insert,
    "Key.left": Key.left,
    "Key.menu": Key.menu,
    "Key.num_lock": Key.num_lock,
    "Key.page_down": Key.page_down,
    "Key.page_up": Key.page_up,
    "Key.pause": Key.pause,
    "Key.print_screen": Key.print_screen,
    "Key.right": Key.right,
    "Key.scroll_lock": Key.scroll_lock,
    "Key.shift": Key.shift,
    "Key.shift_l": Key.shift_l,
    "Key.shift_r": Key.shift_r,
    "Key.space": Key.space,
    "Key.tab": Key.tab,
    "Key.up": Key.up
}

pynput_special_buttons = {
    "Button.left": Button.left,
    "Button.right": Button.right,
    "Button.middle": Button.middle
}

def run_macro(macro, delay=2):
    sleep(delay)

    for action in macro:
        match action["type"]:
            case "wait":
                sleep(action["duration"] / 1000.0)
            case "key_press":
                key = action["key"]
                kc.press(pynput_special_keys.get(key, key))
            case "key_release":
                key = action["key"]
                kc.release(pynput_special_keys.get(key, key))
            case "mouse_movement":
                mkey.move_to(int(action["x"]), int(action["y"]))
            case "mouse_press":
                mc.press(pynput_special_buttons[action["button"]])
            case "mouse_release":
                mc.release(pynput_special_buttons[action["button"]])
            case "mouse_scroll":
                if "x" in action:
                    mkey.move_to(int(action["x"]), int(action["y"]))
                mc.scroll(action["dx"], action["dy"])


macro_actions = [{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 7},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1501},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 3442},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 146},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 406},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 169},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 175},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 152},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 54},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 144},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 81},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 79},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 101},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 77},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 255},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 172},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 342},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 283},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 1625},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 196},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 445},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 94},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 188},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 154},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 2},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 274},
{'type': 'key_press', 'key': 'd'},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 60},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 257},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 45},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 3},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 333},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 36},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 189},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 11},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 355},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 68},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 106},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 216},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 217},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 24},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 242},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 402},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 207},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 164},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 301},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 50},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 157},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 388},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 155},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 282},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 92},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 386},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 168},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 444},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 315},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 571},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 395},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 134},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 205},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 170},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 295},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 78},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 104},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 404},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 680},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 21},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 138},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 152},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 177},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 125},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 111},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 80},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 107},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 163},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 200},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 54},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 115},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 890},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 98},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 853},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 39},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 208},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 153},
{'type': 'key_release', 'key': 'w'},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 302},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 16},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 16},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 195},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 40},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 14},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 275},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 106},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 250},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 131},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 215},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 2},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 248},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 67},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 315},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 130},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 145},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 129},
{'type': 'key_release', 'key': 'w'}]

if __name__ == "__main__":
    run_macro([{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 7},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1501},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 3442},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 146},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 406},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 169},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 175},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 152},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 54},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 144},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 81},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 79},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 101},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 77},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 255},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 172},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 342},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 283},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 1625},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 196},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 445},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 94},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 188},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 154},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 2},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 274},
{'type': 'key_press', 'key': 'd'},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 60},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 257},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 45},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 3},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 333},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 36},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 189},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 11},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 355},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 68},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 106},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 216},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 217},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 24},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 242},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 402},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 207},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 164},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 301},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 50},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 157},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 388},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 155},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 282},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 92},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 386},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 168},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 444},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 315},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 571},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 395},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 134},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 205},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 170},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 295},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 78},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 104},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 404},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 680},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 21},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 138},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 152},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 177},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 125},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 111},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 80},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 107},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 163},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 200},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 54},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 115},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 890},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 98},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 853},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 39},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 208},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 153},
{'type': 'key_release', 'key': 'w'},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 302},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 16},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 16},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 195},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 40},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 14},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 275},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 106},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 250},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 131},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 215},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 2},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 248},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 67},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 315},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 130},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 145},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 129},
{'type': 'key_release', 'key': 'w'}])