# Made using ReTask by JustSoftware & cresqnt

CPU_INTENSIVE_HIGH_ACCURACY_SLEEP = True
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController
from mousekey import MouseKey
from time import sleep, perf_counter

kc = KeyboardController()
mc = MouseController()
mkey = MouseKey()

pynput_special_keys = {
    "Key.alt": Key.alt,
    "Key.alt_l": Key.alt_l,
    "Key.alt_r": Key.alt_r,
    "Key.backspace": Key.backspace,
    "Key.caps_lock": Key.caps_lock,
    "Key.cmd": Key.cmd,
    "Key.cmd_l": Key.cmd_l,
    "Key.cmd_r": Key.cmd_r,
    "Key.ctrl": Key.ctrl,
    "Key.ctrl_l": Key.ctrl_l,
    "Key.ctrl_r": Key.ctrl_r,
    "Key.delete": Key.delete,
    "Key.down": Key.down,
    "Key.end": Key.end,
    "Key.enter": Key.enter,
    "Key.esc": Key.esc,
    "Key.f1": Key.f1,
    "Key.f2": Key.f2,
    "Key.f3": Key.f3,
    "Key.f4": Key.f4,
    "Key.f5": Key.f5,
    "Key.f6": Key.f6,
    "Key.f7": Key.f7,
    "Key.f8": Key.f8,
    "Key.f9": Key.f9,
    "Key.f10": Key.f10,
    "Key.f11": Key.f11,
    "Key.f12": Key.f12,
    "Key.home": Key.home,
    "Key.insert": Key.insert,
    "Key.left": Key.left,
    "Key.menu": Key.menu,
    "Key.num_lock": Key.num_lock,
    "Key.page_down": Key.page_down,
    "Key.page_up": Key.page_up,
    "Key.pause": Key.pause,
    "Key.print_screen": Key.print_screen,
    "Key.right": Key.right,
    "Key.scroll_lock": Key.scroll_lock,
    "Key.shift": Key.shift,
    "Key.shift_l": Key.shift_l,
    "Key.shift_r": Key.shift_r,
    "Key.space": Key.space,
    "Key.tab": Key.tab,
    "Key.up": Key.up
}

pynput_special_buttons = {
    "Button.left": Button.left,
    "Button.right": Button.right,
    "Button.middle": Button.middle
}

def run_macro(macro, delay=2):
    sleep(delay)

    for action in macro:
        match action["type"]:
            case "wait":
                sleep(action["duration"] / 1000.0)
            case "key_press":
                key = action["key"]
                kc.press(pynput_special_keys.get(key, key))
            case "key_release":
                key = action["key"]
                kc.release(pynput_special_keys.get(key, key))
            case "mouse_movement":
                mkey.move_to(int(action["x"]), int(action["y"]))
            case "mouse_press":
                mc.press(pynput_special_buttons[action["button"]])
            case "mouse_release":
                mc.release(pynput_special_buttons[action["button"]])
            case "mouse_scroll":
                if "x" in action:
                    mkey.move_to(int(action["x"]), int(action["y"]))
                mc.scroll(action["dx"], action["dy"])


macro_actions = [{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 6},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 3066},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 6246},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 67},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 609},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 281},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 172},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 123},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 224},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 148},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 46},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 227},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 130},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 89},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 107},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 68},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 370},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 193},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 681},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 654},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 3416},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 192},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 555},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 465},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 192},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 711},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 198},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 505},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 113},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 179},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 145},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 254},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 21},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 218},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 417},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 173},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 605},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 131},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 1105},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 192},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 465},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1574},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 462},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 197},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 594},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 210},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 629},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 313},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 737},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 221},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 385},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 236},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 577},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 1099},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 54},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 216},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 188},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 199},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 232},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 143},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 16},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 229},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 149},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 131},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 54},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 210},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 1351},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 95},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 1520},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 248},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 210},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 351},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 310},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 308},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 342},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 188},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 447},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 248},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 214},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 240},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 19},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 222},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 25},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 294},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 32},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 139},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 1034},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 103},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 200},
{'type': 'key_release', 'key': 'w'}]

if __name__ == "__main__":
    run_macro(macro_actions)