# Made using ReTask by JustSoftware & cresqnt

CPU_INTENSIVE_HIGH_ACCURACY_SLEEP = True
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController
from mousekey import MouseKey
from time import sleep, perf_counter
from fractions import Fraction

NONVIP = False
SCALE = float(Fraction(342, 277))

def preprocess_macro(macro, nonvip=True):
    processed = []
    for action in macro:
        if action["type"] == "wait":
            new_action = action.copy()
            if nonvip:
                new_action["duration"] = (action["duration"] * SCALE)
            processed.append(new_action)
        else:
            processed.append(action.copy())
    return processed

kc = KeyboardController()
mc = MouseController()
mkey = MouseKey()


pynput_special_keys = {
    "Key.alt": Key.alt,
    "Key.alt_l": Key.alt_l,
    "Key.alt_r": Key.alt_r,
    "Key.backspace": Key.backspace,
    "Key.caps_lock": Key.caps_lock,
    "Key.cmd": Key.cmd,
    "Key.cmd_l": Key.cmd_l,
    "Key.cmd_r": Key.cmd_r,
    "Key.ctrl": Key.ctrl,
    "Key.ctrl_l": Key.ctrl_l,
    "Key.ctrl_r": Key.ctrl_r,
    "Key.delete": Key.delete,
    "Key.down": Key.down,
    "Key.end": Key.end,
    "Key.enter": Key.enter,
    "Key.esc": Key.esc,
    "Key.f1": Key.f1,
    "Key.f2": Key.f2,
    "Key.f3": Key.f3,
    "Key.f4": Key.f4,
    "Key.f5": Key.f5,
    "Key.f6": Key.f6,
    "Key.f7": Key.f7,
    "Key.f8": Key.f8,
    "Key.f9": Key.f9,
    "Key.f10": Key.f10,
    "Key.f11": Key.f11,
    "Key.f12": Key.f12,
    "Key.home": Key.home,
    "Key.insert": Key.insert,
    "Key.left": Key.left,
    "Key.menu": Key.menu,
    "Key.num_lock": Key.num_lock,
    "Key.page_down": Key.page_down,
    "Key.page_up": Key.page_up,
    "Key.pause": Key.pause,
    "Key.print_screen": Key.print_screen,
    "Key.right": Key.right,
    "Key.scroll_lock": Key.scroll_lock,
    "Key.shift": Key.shift,
    "Key.shift_l": Key.shift_l,
    "Key.shift_r": Key.shift_r,
    "Key.space": Key.space,
    "Key.tab": Key.tab,
    "Key.up": Key.up
}

pynput_special_buttons = {
    "Button.left": Button.left,
    "Button.right": Button.right,
    "Button.middle": Button.middle
}

def run_macro(macro, delay=2):
    sleep(delay)

    for action in macro:
        match action["type"]:
            case "wait":
                sleep(action["duration"] / 1000.0)
            case "key_press":
                key = action["key"]
                kc.press(pynput_special_keys.get(key, key))
            case "key_release":
                key = action["key"]
                kc.release(pynput_special_keys.get(key, key))
            case "mouse_movement":
                mkey.move_to(int(action["x"]), int(action["y"]))
            case "mouse_press":
                mc.press(pynput_special_buttons[action["button"]])
            case "mouse_release":
                mc.release(pynput_special_buttons[action["button"]])
            case "mouse_scroll":
                if "x" in action:
                    mkey.move_to(int(action["x"]), int(action["y"]))
                mc.scroll(action["dx"], action["dy"])

macro_actions = [{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 1},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 3291},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 2526},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 165},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 794},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 247},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 174},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 166},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 143},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 124},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 94},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 147},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 153},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 96},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 113},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 31},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 225},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 204},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 862},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 1144},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 4800},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 2148},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 188},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 113},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 269},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 90},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 575},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 1063},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 272},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 319},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 145},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 240},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 187},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 160},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 127},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 163},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 12},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 206},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 507},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 57},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 137},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 188},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 57},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 232},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 1000},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 214},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 431},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 155},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 526},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 665},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 114},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 188},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 740},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 175},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 1596},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 121},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 102},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 98},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 83},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 295},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 68},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 142},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 1193},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 141},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 151},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 140},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 705},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 106},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 581},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 219},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 179},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 133},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 41},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 129},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 266},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 131},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 57},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 140},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 137},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 195},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 181},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 51},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 541},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 317},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 4},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 181},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 109},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 27},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 282},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 280},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 124},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 36},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 542},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 167},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 463},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 213},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 594},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 192},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 305},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 198},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 25},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 220},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 238},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 180},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 563},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 193},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 133},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 269},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 112},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 239},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 47},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 94},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 2055},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 325},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 142},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 201},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 896},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 226},
{'type': 'key_release', 'key': 's'},
{'type': 'wait', 'duration': 16},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 172},
{'type': 'key_press', 'key': 'w'},
{'type': 'wait', 'duration': 338},
{'type': 'key_release', 'key': 'w'},
{'type': 'wait', 'duration': 143},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 67},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 114},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 601},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 153},
{'type': 'key_press', 'key': 'Key.space'},
{'type': 'wait', 'duration': 84},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 101},
{'type': 'key_release', 'key': 'Key.space'},
{'type': 'wait', 'duration': 336},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 510},
{'type': 'key_press', 'key': 's'},
{'type': 'wait', 'duration': 862},
{'type': 'key_press', 'key': 'a'},
{'type': 'wait', 'duration': 456},
{'type': 'key_release', 'key': 'a'},
{'type': 'wait', 'duration': 338},
{'type': 'key_press', 'key': 'd'},
{'type': 'wait', 'duration': 1060},
{'type': 'key_release', 'key': 'd'},
{'type': 'wait', 'duration': 309},
{'type': 'key_release', 'key': 's'}]

macro_actions = preprocess_macro(macro_actions, NONVIP)

if __name__ == "__main__":
    run_macro(macro_actions)